language: csharp
solution: CatSkald.Roguelike.sln

env:
- DOTNET_INSTALL_DIR="$PWD/.dotnetcli"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: latest
      env: DOTNETCORE=1
    - dotnet: 1.0.1
      mono: none
      env: DOTNETCORE=1

before_script:
  - chmod +x ./build.sh
      
script:
  - cd "$TRAVIS_BUILD_DIR"
  - ./build.sh
