language: csharp
solution: CatSkald.Roguelike.sln

env:
- DOTNET_INSTALL_DIR="dotnet.exe"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: latest
      env: DOTNETCORE=1

before_script:
  - chmod +x ./build.sh
      
script:
  - cd "$TRAVIS_BUILD_DIR"
  - ./build.sh
