language: csharp
solution: CatSkald.Roguelike.sln
dotnet: 2.1.504
dist: trusty
sudo: required
mono: latest

env:
- DOTNET_INSTALL_DIR="dotnet"

before_script:
  - mv ./build/* ./
  - chmod +x ./fake.sh
      
script:
  - cd "$TRAVIS_BUILD_DIR"
  - ./build/fake.sh
