language: csharp
solution: CatSkald.Roguelike.sln
dotnet: 2.0.0
mono: none
dist: trusty

env:
- DOTNET_INSTALL_DIR="dotnet"

before_script:
  - chmod +x ./build.sh
      
script:
  - cd "$TRAVIS_BUILD_DIR"
  - ./build.sh
