language: csharp
solution: CatSkald.Roguelike.sln

matrix:
  include:
    - dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1

script:
  - chmod +x ./build.sh
  - cd scripts && ./build.sh
