language: csharp
solution: CatSkald.Roguelike.sln

env:
- DOTNET_INSTALL_DIR="dotnet"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 2.0.0
      mono: latest
    - dotnet: 2.0.0
      mono: none

before_script:
  - chmod +x ./build.sh
      
script:
  - cd "$TRAVIS_BUILD_DIR"
  - ./build.sh
