language: csharp
solution: CatSkald.Roguelike.sln
install:
  - nuget restore
  - nuget OpenCover -OutputDirectory tools
  - nuget install coveralls.net -OutputDirectory tools
  - nuget install xunit.runners -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release CatSkald.Roguelike.sln
  - mono ./tools/OpenCover.*/tools/opencover.console.exe -register:user -target:"./testrunner/xunit.runners.2.0.0/tools/xunit.console.exe" -targetargs:"test/CatSkald.Roguelike.Test.Core.UnitTests" -output:coverage.xml -mergeoutput -oldstyle
  - mono ./tools/OpenCover.*/tools/opencover.console.exe -register:user -target:"./testrunner/xunit.runners.2.0.0/tools/xunit.console.exe" -targetargs:"test/CatSkald.Roguelike.Test.DungeonGenerator.UnitTests" -output:coverage.xml -mergeoutput -oldstyle
