language: csharp
solution: CatSkald.Roguelike.sln

matrix:
  include:
    - dotnet: 1.0.0-preview2-003121
      mono: none
      sudo: required
      env: DOTNETCORE=1
    - mono: latest

script:
  - chmod +x ./build.sh
