version: 0.0.1-alpha.{build}
skip_tags: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: CBhcWnE/wJeVYaOS+wmXcIkIzs39TOpQGFncxiXsSEOHGHf1nghMHgdk/LNX8oiT
  SONARQUBE_TOKEN:
    secure: id3AQevkzEdbYj60D7/A9tr1AdNEYU39IuHz5nO7zAEzWgy06bKrOzM5BVwyyEEE
before_build:
  - cmd: appveyor-retry dotnet restore -v Minimal
build_script:
  - cmd: .\build\build.cmd
test: off
artifacts:
  - path: 'output\*.nupkg'
    name: NuGetPackages