skip_tags: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: CBhcWnE/wJeVYaOS+wmXcIkIzs39TOpQGFncxiXsSEOHGHf1nghMHgdk/LNX8oiT
  SONARQUBE_TOKEN:
    secure: id3AQevkzEdbYj60D7/A9tr1AdNEYU39IuHz5nO7zAEzWgy06bKrOzM5BVwyyEEE
before_build:
  - cmd: move .\build\* .\
build_script:
  - cmd: .\fake.cmd
test: off
artifacts:
  - path: 'output\*.nupkg'
    name: NuGetPackages